# Prometheus (Deployment), prometheus
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  serviceAccountName: prometheus-k8s
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 2
  image: quay.io/prometheus/prometheus:v2.20.0
  version: v2.20.0
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  podMonitorNamespaceSelector: {}
  probeNamespaceSelector: {}
  probSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
