# Service, prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  selector:
    app: prometheus
    prometheus: k8s
  ports:
  - name: web
    port: 9090
    targetPort: web
  sessionAffinity: ClientIP
