# ServiceMonitor, prometheus-adapter
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-adapter
  namespace: monitoring
  labels:
    name: prometheus-adapter
spec:
  endpoints:
  - bearerTokenFile: /var/run/secretes/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      name: prometheus-adapter