# PVC define, only for prometheus
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: nfs-dynamic-pvc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
