# grafana-pvc.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.176.8
    path: /appdata/nfs/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
