# ClusterRoleBinding, StorageClass
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-nfs-client-provisioner-monitoring
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner-monitoring
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner-monitoring
  apiGroup: rbac.authorization.k8s.io
