# RBAC ClusterRole kube-state-metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-explorer
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorizations.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create