# RBAC ClusterRoleBinding kube-state-metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-explorer
subjects:
- kind: ServiceAccount
  name: node-explorer
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-explorer