# ServiceMonitor kube-state-metrics
# ServiceMonitor: expose monitor on service, including ports, networks ...
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 1.9.7
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  jobLabel: app.kubernetes.io/name
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/totken
      honorLables: true
      interval: 30s
      port: https-main
      relabelings:
        - action: labeldrop
          regex: (pod|service|endpoint|namespace)
      schema: https
      scrapeTimeout: 30s
      tlsConfig:
        insecureSkipVerify: true
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: https-self
      schema: https
      tlsConfig:
        insecureSkipVerify: true