apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    k8s-app: busybox
    version: v1.28.3
spec:
  selector:
    matchLabels:
      k8s-app: busybox
  template:
    metadata:
      name: busybox
      labels:
        k8s-app: busybox
        version: v1.28.3
    spec:
      containers:
      - name: busybox
        image: ${DOCKER_HUB}/busybox:1.28.3
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "3600"
