# RBAC roleBinding, stroage
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-locking-nfs-client-provisioner
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner-monitoring
  namespace: monitoring
roleRef:
  kind: Role
  name: leader-locking-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io
