apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  template:
    metadata:
      labels:
        k8s-app: node-exporter
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: node-exporter
        image: docker-hub:5000/prom/node-exporter:v1.0.1
        ports:
        - name: http
          protocol: TCP
          containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    k8s-app: node-exporter
spec:
  type: NodePort
  selector:
    k8s-app: node-exporter
  ports:
  - name: http
    protocol: TCP
    port: 9100
    nodePort: 31672
