# Deployment, Storage Provisioner
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner-monitoring
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nfs-provisioner-monitoring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: nfs-provisioner-monitoring
    spec:
      serviceAccountName: nfs-client-provisioner-monitoring
      containers:
      - name: nfs-client-provisioner-monitoring
        #image: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
        image: docker-hub:5000/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
        imagePullPolicy: IfNotPresent
        env:
        - name: PROVISIONER_NAME
          # this value is provided to storageclass calling
          value: nfs-provisioner-monitoring
        - name: NFS_SERVER
          value: 192.168.186.8
        - name: NFS_PATH
          value: /appdata/nfs
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
      volumes:
      - name: nfs-client-root
        nfs:
          server: 192.168.176.8
          path: /appdata/nfs
