apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config-7.9.1
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  elasticsearch.yml: |-
    cluster.name: kubernetes-logging
    node.name: elasticsearch-logging-0
    path.data: /data
    discovery.type: single-node
    network.host: 0.0.0.0
