apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: ${KUBE_PROXY_ADDRESS}
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: ${KUBE_PROXY_KUBECONFIG}
  qps: 5
clusterCIDR: ${KUBE_CLUSTER_CIDR}
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ${KUBE_PROXY_ADDRESS}:10256
hostnameOverride: ${KUBE_PROXY_ADDRESS}
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: ""
  minSyncPeriod: 5s
  scheduler: rr
  strictARP: false
  syncPeriod: 30s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ${KUBE_PROXY_ADDRESS}:10249
mode: ${KUBE_PROXY_MODE}
nodePortAddresses: null
oomScoreAdj: -999
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 250ms
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
