apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---
# PodPreset: setting tz for namespace
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-tz-env
  namespace: mysql
spec:
  selector:
    matchLabels:
  env:
  - name: TZ
    value: Asia/Shanghai
