---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    version: v8.0.24
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: v8.0.24
  template:
    metadata:
      labels:
        app: mysql
        version: v8.0.24
    spec:
      containers:
      - name: mysql
        image: ${DOCKER_HUB}/mysql/mysql-server:8.0.24
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-pwd
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 33060
          name: mysqlx
        volumeMounts:
        - name: mysql-var-lib
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-var-lib
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: nfs-dynamic-mysql
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    version: v8.0.24
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  - port: 33060
    protocol: TCP
    name: mysqlx
  selector:
    app: mysql
