# Service alertmanager
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    alertmanager: main
spec:
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: ClientIP
  ports:
  - name: web
    port: 9903
    targetPort: web