apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: docker-hub:5000/grafana/grafana:7.1.3
        imagePullPolicy: IfNotPresent
        env: []
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
          readOnly: false
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: false
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: false
        - name: grafana-dashboard-apiserver
          mountPath: /grafana-dashboard-definitions/0/apiserver
          readOnly: false
        - name: grafana-dashboard-cluster-total
          mountPath: /grafana-dashboard-definitions/0/cluster-total
          readOnly: false
        - name: grafana-dashboard-controller-manager
          mountPath: /grafana-dashboard-definitions/0/controller-manager
          readOnly: false
        - name: grafana-dashboard-k8s-resources-cluster
          mountPath: /grafana-dashboard-definitions/0/k8s-resources-cluster
          readOnly: false
        - name: grafana-dashboard-k8s-resources-namespace
          mountPath: /grafana-dashboard-definitions/0/k8s-resources-namespace
          readOnly: false
        - name: grafana-dashboard-k8s-resources-node
          mountPath: /grafana-dashboard-definitions/0/k8s-resources-node
          readOnly: false
        - name: grafana-dashboard-k8s-resources-pod
          mountPath: /grafana-dashboard-definitions/0/k8s-resources-pod
          readOnly: false
        - name: grafana-dashboard-k8s-resources-workload
          mountPath: /grafana-dashboard-definitions/0/k8s-resources-workload
          readOnly: false
        - name: grafana-dashboard-k8s-resources-workloads-namespace
          mountPath: /grafana-dashboard-definitions/0/k8s-resources-workloads-namespace
          readOnly: false
        - name: grafana-dashboard-kubelet
          mountPath: /grafana-dashboard-definitions/0/kubelet
          readOnly: false
        - name: grafana-
