apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  namespace: monitoring
spec:
  storageClassName: nfs-dynamic-monitoring
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
