apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-secret
  namespace: mysql
  labels:
    k8s-app: mysql
data:
  # ocab7e9a
  root-pwd: "b2NhYjdlOWE="
  # dev
  db-name: "ZGV2"
  db-user-name: "ZGV2"
  db-user-pwd: "ZGV2"
