# PodPreset: setting tz for default namespace
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-tz-env
spec:
  selector:
    matchLabels:
  env:
  - name: TZ
    value: Asia/Shanghai

---
# PodPreset: setting tz for kube-system namespace
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-tz-env
  namespace: kube-system
spec:
  selector:
    matchLabels:
  env:
  - name: TZ
    value: Asia/Shanghai
